### ISSUE TITLE
Template Configuration for AtomS3 Lite + Atomic RS485 Base

### ISSUE THREAD

**Issue by alexdelprete** [alexdelprete/HA-NeoPool-MQTT#10]
@curzon01 Hi Norbert, @Danton73 has ordered an AtomS3 Lite instead of the Atom Lite. And he bought the Atomic RS485 base instead of the Tail485.

![image](https://github.com/arendst/Tasmota/assets/7027842/b5f751bd-ff91-4b35-a2b0-9e8ec256cd5c)

I checked the docs and the pins for the Atomic RS485 are these:

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/489e9f58-6f5f-45e4-a3b3-970dec631337)

What template configuration should he use? I'm trying to direct him to a manual configuration of GPIOs now, but a Template config would be better I think.

Also: is there a way at compilation time, in `user_config_override.h` to detect a specific chip type? 

The Atom Lite uses a ESP32-PICO-D4 while his device uses the ESP32-S3, in order to have different templates the cpu family is not enough unfortunately.

Thanks for the help.

**Comment by curzon01** [comment]
> Template config would be better I think

```
Template {"NAME":"AtomS3 Lite + Atomic RS485 Base","GPIO":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6976,0,0,7008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":1}
```

> is there a way at compilation time, in user_config_override.h to detect a specific chip type?

Automatic detection is not possible and user_config_override.h is the wrong place to select this, it needs another environment to compile code for this chip type.

You have to select the correct Platform IO environment to compile the binary file for an ESP S3 chip (as it's done by Tasmota for [all binaries](https://ota.tasmota.com/tasmota32/release/), for an ESP32 S3 you must also select tasmota32s3.bin for this chip type):

- when using VSC, select "env:tasmota32s3" in the bottom line
Change the default
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/6636844/3e5671c7-fd68-461d-b7e1-9f8934b0faf4) 
to
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/6636844/e9c35f72-7978-4cdb-b904-1316cccf279d)

- when using other compiling environments (this works also with VSC), copy the file "platform_override_sample.ini" to "platform_override.ini" within the base tasmota directory, under "default_envs" disable the line "tasmota" with a semicolon in front and enable "tasmota32s3" by removing the semicolon:
```ini
default_envs            =
; *** Uncomment the line(s) below to select version(s)
;                          tasmota
...
                          tasmotas32s3
...
```

**Comment by alexdelprete** [comment]
I already compiled the bin for the AtomS3 Lite using Tasmocompiler, that supports the chip, luckily. It's way faster than when I compile with VS Code, and simpiler for the average user. He flashed it correctly, Tasmota is working fine. But Template is messed up because it uses the Atom Lite config.

What I was aiming to do is, like for the Atom Lite and ESP8266, have in `user_config_override` a way to conditionally configure the Template. So that users could compile, add all the options, and have a working bin preconfigured.

I'm doing this now:

```C
// Define Template based on chip
#ifdef USER_TEMPLATE
  #undef USER_TEMPLATE
#endif

#ifdef ESP32
  #define USER_TEMPLATE "{\"NAME\":\"NeoPool Atom Lite + Tail485\",\"GPIO\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,6976,0,0,0,0,0,7008,1,0,0,0,0,0,0],\"FLAG\":0,\"BASE\":1}"
#endif  // ESP32

#ifdef ESP8266
  #define USER_TEMPLATE "{\"NAME\":\"NeoPool ESP8266\",\"GPIO\":[1,6528,1,6496,1,1,0,0,1,1,1,1,1,1],\"FLAG\":0,\"BASE\":18}"
#endif  // ESP8266

// [Module] Select default model (the list is kModuleNiceList() in file tasmota_template.h) USER_MODULE is the TEMPLATE
#ifdef MODULE
  #undef MODULE
#endif
#define MODULE                 USER_MODULE

// Select the default model as FALLBACK when the user does a RESET 1
#ifdef FALLBACK_MODULE
  #undef FALLBACK_MODULE
#endif
#define FALLBACK_MODULE        USER_MODULE
```

**Comment by curzon01** [comment]
ahh, got it

you can distinguish this using CONFIG_IDF_TARGET_ESP32S3:

#ifdef ESP32
  #ifdef CONFIG_IDF_TARGET_ESP32S3
    #define USER_TEMPLATE '{"NAME":"AtomS3 Lite + Atomic RS485 Base","GPIO":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6976,0,0,7008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"FLAG":0,"BASE":1}'
  #else
    #define USER_TEMPLATE "{\"NAME\":\"NeoPool Atom Lite + Tail485\",\"GPIO\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,6976,0,0,0,0,0,7008,1,0,0,0,0,0,0],\"FLAG\":0,\"BASE\":1}"
  #endif // CONFIG_IDF_TARGET_ESP32S3
#endif  // ESP32

**Comment by alexdelprete** [comment]
@curzon01 Norbert, @Danton73 flashed the new bin with the updated template but he got this config:

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/873d7829-836b-44f4-92e7-4a78a9ea10ff)

We were expecting GPIO19 TX and GPIO22 RX. What could be the issue?

**Comment by alexdelprete** [comment]
> However, if you plug an M5Stack AtomS3 Lite into it, the description "PinMap" on its page is no longer correct.

Since in the docs they specify the base is compatible with `ATOM Matrix/ATOM Lite/ATOMS3/ATOMS3 Lite` and since they provide a single "PinMap", I assumed it was correct.

For the Tail485 it was correct, at least for the Atom Lite (don't know for AtomS3 Lite). Should we report them the issue?

> Nobody knows what we are see in the screenshot above. Is this a screenshot of the template or of "Configuration/Configure Module" and if, what

It is the template page. I'm discussing with him in [this thread](https://community.home-assistant.io/t/ha-neopool-mqtt-integration-of-tasmota-neopool-for-sugar-valley-hayward-aquarite-bayrol-devices/632517/30).

I told him to do what you asked, let's see...

**Comment by alexdelprete** [comment]
Found the issue: the PinMap reported by the Atomic Base documentation works only for Atom Lite.

Here's the pins of the Atomic base:

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/ececc6fd-64a4-4731-a50c-d428aa7b509c)

Here's the diagram of the connections of the Atomic Lite, and you can see that the two connection pins, if used  with the Atomic Base, are indeed GPIO19-TX and GPIO22-RX

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/7f80773f-4225-4049-a744-48e8103d6ba0)

On AtomS3 Lite instead, like you explained, they are GPIO5-RX and GPIO6-TX:

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/f6b79e0a-9b2e-4639-8216-ac675b0db641)

I took for granted the PinMap was valid for ALL compatible devices. Thanks for the heads-up. :)

**Comment by curzon01** [comment]
that's a limit providing ready templates for this combination:
- AtomS3 Lite + Atomic RS485 it's GPIO5/6
- AtomS3 Lite + Tail485 it's GPIO1/2
but you can't distinguish that in user_config_override.h

**Comment by curzon01** [comment]
in general user have to set a define manually if they are using a Atomic RS485 or Tail485, CPU can be auto select

**Comment by alexdelprete** [comment]
@curzon01 Norbert, @Danton73 just wrote it is working fine. :)

What do we need from him to create the template? I'd like to update docs and possibly the `user_config.override.h`.

Thanks...

**Comment by curzon01** [comment]
template for S3 based on info given is

```
Template {“NAME”:“NeoPool AtomS3 Lite + Atomic RS485 Base”,“GPIO”:[0,0,0,0,0,7008,6976,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],“FLAG”:0,“BASE”:1}
```

If you want to let him try, he should input this command and verify under in GUI Template if GPIO5 = NeoPool Rx and GPIO6 is NeoPool Tx. If so, activate it using `Module 0`
