### ISSUE TITLE
Read/Set filtration interval

### ISSUE THREAD

**Issue by mnaiman** [alexdelprete/HA-NeoPool-MQTT#12]
Hi,

is it possible to implement Filtration intervals?

https://tasmota.github.io/docs/NeoPool/#examples

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/2264442/ecf55772-daab-4f0e-857f-1c883f6a2437)

Thanks

**Comment by curzon01** [comment]
On Tasmota side it is available using berry enhancement, then you can use NPTimer1-3, see [ESP32: Adding user defined NeoPool commands to Tasmota](https://tasmota.github.io/docs/NeoPool/#esp32-adding-user-defined-neopool-commands-to-tasmota) -`NPTimer<x>`

If you use an ESP8266, it's not available at all

**Comment by mnaiman** [comment]
Yes I know, but could be achieved by using NPRead command via MQTT without berry for ESP8266

**Comment by alexdelprete** [comment]
> Yes I know, but could be achieved by using NPRead command via MQTT without berry for ESP8266

Why don't you use HA to schedule things? One of the purposes I made the integration of NeoPool for, was to leverage HA functionalities.

For scheduling I'm using [Scheduler Component](https://github.com/nielsfaber/scheduler-component) with the [Scheduler Card](https://github.com/nielsfaber/scheduler-card).
