### ISSUE TITLE
Hayward Heat pump integration

### ISSUE THREAD

**Issue by stepsolar** [alexdelprete/HA-NeoPool-MQTT#14]
Hi Alex, with these protocols would it be possible to also integrate the Hayward heat pump via Modbus?

[Heat Pump Protocol 51](https://www.dropbox.com/scl/fi/x1e84b0s252kjkmh3zsu2/302020-00000028-communication-protocol.xls?dl=0&rlkey=6yue0nh1y0o0o6kw7mwpglpan)

https://docs.google.com/document/d/e/2PACX-1vTeQRtc3AX4VB80hpf8HlfPtUTnXznXPVtW3zGL3Krl7_H51Z1tFqnpi417Iw0vtOvZ7oqZBjtkIbFl/pub

**Comment by alexdelprete** [comment]
NeoPool driver already supports the heatpump: https://tasmota.github.io/docs/NeoPool/

**Comment by stepsolar** [comment]
I didn't understand how to make it work what you suggest. 
The heat pump has its own wifi module and app for control.
In my opinion, you can retrieve the values I read with apps, such as temperature and more.

**Comment by curzon01** [comment]
that's a missunderstanding

NeoPool HEATING is only the heating mode of Sugar Valley Pool systems, it does not communicate with any heat pump. NeoPool does not support heat pump protocols.

@stepsolar This integration does not communicate with any hardware directly, it uses the Tasmota with NeoPool module via MQTT. Tasmota with NeoPool module communicates with the hardware and provides get/set commands via MQTT. It supports a lot of Sugar Valley pool systems protocols but no heat pumps.

**Comment by stepsolar** [comment]
But could you put a tasmota module on the heat pump and communicate directly with it? Maybe I found the pump codes you could add to tasmota?

**Comment by curzon01** [comment]
Yeah, this is theoretically possible, but do you have any idea how much work it takes? Unfortunately, I don't have the time for, sorry

**Comment by CosminFRC** [comment]
@stepsolar  You can buy an wireless module for your Hayward heat pump (a Hayward branded one or a "generic" one) and use the Aqua Temp app and Aqua Temp integration in HA.
Here's a link with the generic WIFI module, same as the Hayward branded one but at afraction of price:
https://heatpumps4pools.com/product/thermotec-inverter-wifi-module/

**Comment by Karel311** [comment]
Maybe you can just connect your heat pump with the AUX switch on the sugar valley to switch between    on / standby

 I put the heat pump on max. temperature and arrange pool temperature via the oxilife this way.
