### ISSUE TITLE
creating a sensor when pool pump flow is running

### ISSUE THREAD

**Issue by Karel311** [alexdelprete/HA-NeoPool-MQTT#15]
Hi, 

the flow switch of the pH-electrode has state ON when pool pump is not running (= "FLOW" on display of my oxilife).

How to create an inverted switch in HomeAssistant with ON state when pool pump is running ? This way I know for sure that filtration is on going. 

Already tried to create this sensor in my  configuration.yaml based on the ph_flow_sensor:

`sensor:
  - platform: template
    sensors:
inverted_neopool_mqtt_ph_fl1: 
friendly_name: "Flowsensor pH elektrode" 
value_template: "{{ is_state('binary_sensor.neopool_mqtt_ph_fl1', 'off') }}"'

but this sensor only has state "true"or "false", so the icons don't change color when state changes. 
Any ideas?

**Comment by alexdelprete** [comment]
The flow sensor is an ALARM sensor, so the logic is that when it's 1 it means NO FLOW. When it's 1, the cell stops production.

I also found that we have 2 flow sensors: 

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/77c53c73-5689-46f2-ad93-7d6f6b0ca674)
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/cef120df-b2e4-4a4e-a95d-400840c78c18)

And when I stop the water pump, they both go to state ON.

In my integration I only mapped pH.FL1, not Hydrolisys.FL1, but I suspect they're the same, and one of them has been left for backwards compatibility.

I also forgot to show the FL1 sensor in the lovelace UI files.

SO, getting back to OP: the FL1 is an ALARM, so it's 1 when there's no FLOW. If you prefer an inverted logic, create an inverted state sensor using HA functionalities.

Template to invert:

```
{{ not(states('binary_sensor.neopool_mqtt_ph_fl1') | bool) }}
```

**Comment by alexdelprete** [comment]
You can also invert using [Spook](https://spook.boo/) (recommended custom integration for a lot of stuff), that creates a helper:

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/117c2d3d-efe5-4eba-b71c-80bf356e7ab2)

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/573b793e-9356-47f7-aa50-a4e48c9343f4)

**Comment by curzon01** [comment]
> In my integration I only mapped `pH.FL1`, not `Hydrolisys.FL1`, but I suspect they're the same

It isn't, `pH.FL1` is a firmware logical generated one and does not show the physical flow state. It is also not always in sync with that (this depends of other facts) where `Hydrolisys.FL1` is the physical flow sensor(s).

**Comment by alexdelprete** [comment]
> `pH.FL1` is a firmware logical generated one and does not show the physical flow state.

But why is it tied to the pH? From the Hayward manual I read there is the cell sensor and then the optional flow sensor (mechanical sensor). What does the pH.FL1 actually represent?

> It is also not always in sync

I always see them in sync.

**Comment by alexdelprete** [comment]
I think it would be more appropriate to map the `Hydrolisys.FL1` alarm sensor vs the `pH.FL1`. I'll call it `Flow Alarm`.

And I'll also create a `Water Flow` template binary sensor whose state is the inverse of `Flow Alarm`.

**Comment by alexdelprete** [comment]
Ok, I updated the package:

- Created new Water Flow mqtt binary sensor based on hydrolysis_fl1 binary sensor (inverted state)
- Updated lovelace UI to accomodate Water Flow sensor

@Karel311 please test it and let me know if it works for you.

@curzon01 could you please update the responsive lovelace file with the new sensor? thanks.

**Comment by curzon01** [comment]
> From the Hayward manual I read there is the cell sensor and then the optional flow sensor (mechanical sensor)

As I wrote before, that is exactly what `Hydrolysis.FL1` represent. It is the representation of what you have configured in your system for both sources (may be you don't know, it can be the status of FL1, FL2, FL1 | FL2 or FL1 & FL2).

> What does the pH.FL1 actually represent?

It represents the bitmask bit `MBMSK_PH_STATUS_CTRL_BY_FL` of register `MBF_PH_STATUS` which Sugar Valley describes as following "_Control status of the pH module by flow detection_"

> But why is it tied to the pH?

I think only Sugar Valley could give you the answer.

> I always see them in sync

That can of course be the case, but it doesn't have to be.

My system sometimes reports flow errors via `pH.FL1`, even though there is no flow error also via `Hydrolysis.FL1`. But as I said, I can't tell you why that is.

**Comment by curzon01** [comment]
> could you please update the responsive lovelace file with the new sensor?

If it's possible yes, I'm currently don't often have the time, space or network to work with my laptop for several weeks. My mobile is sufficient for comments, but I don't use it for programming.

**Comment by alexdelprete** [comment]
> It is the representation of what you have configured in your system for both sources (may be you don't know, it can be the status of FL1, FL2, FL1 | FL2 or FL1 & FL2)

Yes I know, I have configured for both as recommended by the installer, that obliged me to install the mechanical flow sensor because he doesn't trust the cell flow detection. FL1 is the cell sensor and FL2 is the mechanical sensor, or the other way around? Can we also configure this programatically?

> It represents the bitmask bit `MBMSK_PH_STATUS_CTRL_BY_FL` of register `MBF_PH_STATUS` which Sugar Valley describes as following "_Control status of the pH module by flow detection_"

Maybe it refers to flow of acid, that's why it's related to pH module: but I'm just speculating...

> If it's possible yes, I'm currently don't often have the time, space or network to work with my laptop for several weeks. My mobile is sufficient for comments, but I don't use it for programming.

Sorry, I didn't know you were in this situation. I'll try to do it myself if that's the case, if I have problems I'll let you know. Thanks.

**Comment by Karel311** [comment]
> Ok, I updated the package:
> 
> * Created new Water Flow mqtt binary sensor based on hydrolysis_fl1 binary sensor (inverted state)
> * Updated lovelace UI to accomodate Water Flow sensor
> 
> @Karel311 please test it and let me know if it works for you. 

Thanks Alex, this worked for me !  
Very appreciated!

**Comment by curzon01** [comment]
> > If it's possible yes, I'm currently don't often have the time, space or network to work with my laptop for several weeks. My mobile is sufficient for comments, but I don't use it for programming.
> 
> Sorry, I didn't know you were in this situation. I'll try to do it myself if that's the case, if I have problems I'll let you know. Thanks.

I just had network and space to set up my laptop, so it's done with the last commits.
