### ISSUE TITLE
Error updating: Invalid file signature

### ISSUE THREAD

**Issue by luixal** [alexdelprete/HA-NeoPool-MQTT#20]
Hi,

When trying to update I'm getting this `Invalid file signature` error:

![image](https://github.com/user-attachments/assets/37201191-1b83-4d8b-9b7b-36fb1367b4ff)

These are the steps I've followed:

1. Download file `NeoPool_ESP32_tasmota32.factory.bin`
2. In the device went into `Firmware Upgrade` menu
3. Selected the file from my local dir
4. Click in `Start upgrade`

Any ideas why this isn't working for me?

Thanks!

PS: This device was already flashed with the firmware downloaded here (as can bee seen in the screenshot at the bottom)

**Comment by curzon01** [comment]
Pls read the README of the firmware folder carefully:

> To update an existing Tasmota device via WebUI...use for ESP32 the files without factory in the filename

use  `NeoPool_ESP32_tasmota32.bin`, the file you used is for initial flash a device, not for updating it via file upload.
