### ISSUE TITLE
Tasmota-NeoPool configuration for Atom Lite + Tail485

### ISSUE THREAD

**Issue by alexdelprete** [alexdelprete/HA-NeoPool-MQTT#4]
@curzon01 I noticed in the updated NeoPool docs that you mention this template configuration:
```console
Template {"NAME":"NeoPool","GPIO":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,6976,0,0,0,0,0,7008,1,0,0,0,0,0,0],"FLAG":0,"BASE":1}
```
While I'm using this one:
```console
Template {"NAME":"NeoPool","GPIO":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6976,0,0,0,0,0,7008,0,0,0,0,0,0,0],"FLAG":0,"BASE":1}
```

I don't know Tasmota well enough to understand the differences, but I think it's due to the fact that I explicitly set ALL GPIOs to `none`, except GPIO26 and GPIO32 obviously. Is it ok?

Other things I wanted to ask about Tasmota, with the objective to easen the installation/configuration process for new users:

1. Would it be possible to add `Tasmota32-NeoPool` to the list of the web flasher?

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/630316c5-35dd-4e9f-8dc4-fd000ecdbcd5)

2. After flashing the custom firmware, is there a way to import/restore a config that contains the Berry scripts and the recommended config parameters so that users could basically do a webflash of NeoPool firmware then restore a config bin file I can provide on the repo that creates the default environment?

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/2f07654f-e4e8-4121-91f2-255e0a9cc464)

Thanks,

Alessandro

**Comment by curzon01** [comment]
> but I think it's due to the fact that I explicitly set ALL GPIOs to none, except GPIO26 and GPIO32 obviously. Is it ok?

If you don't want to use the other possible Atom GPIOs, yes.

From NeoPool doc

> This also allows the later use of the additonal GPIOs 19, 21 - 23 and 33 for other purposes (sensors or similar).

so you get under Tasmota "Configure Module" this
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/6636844/2f91e88b-a24d-4090-a333-01f9a7323294)

and yours is empty

> Would it be possible to add Tasmota32-NeoPool to the list of the web flasher?

No, Tasmota containing NeoPool is not and will not be a default binary.

> After flashing the custom firmware, is there a way to import/restore a config that contains the Berry scripts

Unfortunately not, the scripts must be uploaded manually (my [decode-config](https://github.com/tasmota/decode-config) currently doesn't support ESP user files).

> and the recommended config parameters

You could use decode-config but a simple one line Backlog line should be also enough.

Anyway, I'm not happy with some of the defaults:

- Topic is very environment related (mine are e.g. %prefix%/tasmota/%topic%, because e.g. my Tasmota MQTT user has no access to anything else). E.g. I have to adjust the topics in ha-neopool-mqtt-package.yaml via search and replace. Maybe this should or can be the default?
- TelePeriod 10 should be a workaround.
For example I and many others record MQTT history in a database (e.g. with [mqtt2sql](https://github.com/curzon01/mqtt2sql)). This would lead to a lot of unnecessary records for me. Do you need this realy?

I

**Comment by alexdelprete** [comment]
> and yours is empty

I applied your template, but Configure Module is still empty. Does it need a reboot?

> No, Tasmota containing NeoPool is not and will not be a default binary.

Ok, I'll probably put an already compiled version for the AtomLite on the repo then. Many users have no idea of how to compile a custom firmware, even if they RTFM. :)

> Unfortunately not, the scripts must be uploaded manually (my [decode-config](https://github.com/tasmota/decode-config) currently doesn't support ESP user files).

You're the author of decode-config? Fantastic. :D I was recommending to integrate it in some way to my friend @inverse, TasmoAdmin maintainer, to manage backup/restore. :)

> You could use decode-config but a simple one line Backlog line should be also enough.

Yes, that is true. But Berry files are a potential issue, some friends told me they weren't able to make them work correctly. I have to find an easier way to at least create those 3 .be files. :)

BTW: I still don't understand why Berry scripts are needed, I mean, couldn't those two commands be implemented at driver level like the others?

> * Topic is very environment related

I perfectly understand your objection, but the criteria was letting the average user easily configure HA integration: otherwise they would need to replace the topic everywhere in the package file. I thought: an advanced user would not follow my instructions and replace the topic in the file with no issues, so the target of those instructions is the average user.

> * TelePeriod 10 should be a workaround. Do you need this really?

It is a workaround for issue #3. I don't like it either, but if I use 30s, when you press a switch you wait a lot of time for the ack of the action. The stat/%command% is the proper way, but without the retain flag it creates inconsistency issues on HA restart/reboot/reload.

And again: how many average users record MQTT history? advanced users will simply leave TelePeriod to what they think makes more sense to their environment, knowing that the drawback is that the HA integration will not be quick when activating switch or changing parameters etc.

I mean, users like you don't need me to write a readme. And even if they RTFM, they DTFTWA (do the fuck they want anyways). :)

Did anybody else ever request stat/%command% to be retain flagged? is there a FR for that?

**Comment by curzon01** [comment]
> but Configure Module is still empty. Does it need a reboot?

yes

> I have to find an easier way to at least create those 3 .be files. :)

http request in any way (same as the Tasmota does when you upload it with browser)? Start browser debugger to get the url

> I still don't understand why Berry scripts are needed

is not essential, you can fire the additonal commands also using Backlog `NPWrite xxxx,xxx;NPExec`

> DTFTWA

I didn't know yet, made my day :-)

**Comment by alexdelprete** [comment]
> And I do not want to have conditional basic functionality for both system

I understand...but those two commands seem more relevant than others, like NPControl for example. :D
It would save doing all that stuff with Berry scripts, and maintain them. :)

(I'm trying to convince you...did you notice?)

**Comment by alexdelprete** [comment]
@curzon01 Norbert, is it possible to use a template like the one for Atom, for ESP8266 such that GPIO config is already done after activating the template?

In NeoPool docs [configuration section](https://tasmota.github.io/docs/NeoPool/#configuration) I see only the manual config for ESP8266.

I ask you because I'm preparing a `user_config_override.h` that will automatically configure everything (Rule1 included) so that users won't really have to do anything.

The only problem I have is this: I'm using #ifdef cputype to determine which template to apply, but I don't have the template for ESP8266.

```include
// [Template] Set JSON user template for GPIO configuration (Atom+Tail and ESP8266)
#undef USER_TEMPLATE

#ifdef ESP32
  #define USER_TEMPLATE "{\"NAME\":\"NeoPool Atom Lite + Tail485\",\"GPIO\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,6976,0,0,0,0,0,7008,1,0,0,0,0,0,0],\"FLAG\":0,\"BASE\":1}"
#endif  // ESP32

#ifdef ESP8266
  #define USER_TEMPLATE "{\"NAME\":\"NeoPool ESP8266\",\"GPIO\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,6976,0,0,0,0,0,7008,1,0,0,0,0,0,0],\"FLAG\":0,\"BASE\":1}"
#endif  // ESP8266

// Activate User Template
#define MODULE USER_MODULE
```

**Comment by curzon01** [comment]
> is it possible to use a template

true (if it makes sense)

> In NeoPool docs configuration section I see only the manual config for ESP8266.

'cause it depends on personal hardware config and wiring (unlike Atom Tail, where this is very fixed)


> but I don't have the template for ESP8266

for GPIO1/3 assignment as in the doc this would be

```C++
#define USER_TEMPLATE "{\"NAME\":\"NeoPool ESP8266\",\"GPIO\":[1,6528,1,6496,1,1,0,0,1,1,1,1,1,1],\"FLAG\":0,\"BASE\":18}"
```

- Tasmota GPIO function numbers are different to ESP32 (see [GPIO Overview](https://tasmota.github.io/docs/Components/#gpio-overview))
- possible assignable GPIOs are 0-5, 9-10, 12-17 (I disabled 9 and 10 for usage)
- derived module is 18

**Comment by alexdelprete** [comment]
Thank you. This is the final result, I will test it with a new Atom, unfortunately I don't have an ESP8266 to test it with. If you see something wrong please let me know.

```cpp
// PROJECT is used as the default topic delimiter
#define PROJECT                "SmartPool"

// Disable Tasmota Discovery support [Discover 0] since we'll only use MQTT to integrate in HA
#undef USE_TASMOTA_DISCOVERY

// [Template] Set JSON user template for GPIO configuration (Atom+Tail and ESP8266)
#undef USER_TEMPLATE

#ifdef ESP32
  #define USER_TEMPLATE "{\"NAME\":\"NeoPool Atom Lite + Tail485\",\"GPIO\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,6976,0,0,0,0,0,7008,1,0,0,0,0,0,0],\"FLAG\":0,\"BASE\":1}"
#endif  // ESP32

#ifdef ESP8266
  #define USER_TEMPLATE "{\"NAME\":\"NeoPool ESP8266\",\"GPIO\":[1,6528,1,6496,1,1,0,0,1,1,1,1,1,1],\"FLAG\":0,\"BASE\":18}"
#endif  // ESP8266

// Activate User Template
#define MODULE USER_MODULE

// [DeviceName] Devicename up to 32 characters
#define DEVICE_NAME            PROJECT

// [FriendlyName] Friendlyname up to 32 characters used by webpages and Alexa
#define FRIENDLY_NAME          PROJECT

// [Topic] unique MQTT device topic
#define MQTT_TOPIC             PROJECT

// [MqttClient] Also fall back topic using last 6 characters of MAC address or use "DVES_%12X" for complete MAC address
#define MQTT_CLIENT_ID         PROJECT

// [SensorRetain] Sensor may send retain flag (false = off, true = on)
#define MQTT_SENSOR_RETAIN     true

// Add support for rules (+8k code)
#define USE_RULES

// Add Rule1 data saved at initial firmware load or when command reset is executed
#define USER_RULE1 "ON Time#Initialized DO NPTime 0 ENDON ON Time#Set DO NPTime 0 ENDON ON System#Init DO NPTeleperiod 60 ENDON"

// Activate user Rule1
#define USER_BACKLOG "Rule1 4;Rule1 1;WifiPower 0"

// Log modbus traffic errors: use Weblog 3 or 4 to debug and Weblog 2 to go back to normal log level
// https://github.com/arendst/Tasmota/discussions/18991#discussioncomment-6317229
#undef DEBUG_TASMOTA_SENSOR
#define DEBUG_TASMOTA_SENSOR

// Add support for NeoPool module
#undef USE_NEOPOOL
#define USE_NEOPOOL
```

**Comment by alexdelprete** [comment]
I compiled and tested it on a new Atom, it seems that the configuration is there, but NeoPool commands always result as unknown, it looks like the NeoPool module hasn't been included in the compilation. :(

This happens also when GPIO tx/rx are not configured, but they are actually, so it seems it's a compilation issue, but I'm not sure.

Is there a way to check from tasmo console if the module is included/active?

**Comment by curzon01** [comment]
> Is there a way to check from tasmo console if the module is included

not human readable (located as bit in `Status 4` json `StatusMEM.Features`)

use the program `decode-status.py` from [Tasmota tools](https://github.com/arendst/Tasmota/tree/development/tools) dir: `/tools/decode-status.py -d hostname_or_ip [-p webguipw]`

Outputs
```
Features
  ...
  USE_NEOPOOL
  ...
```

> if the module is active?

that's global Tasmota level so cmnd `GPIO` result should contain "NeoPool Tx" and "NeoPool Rx" on two GPIO _AND_ any NPxxxx cmnd doesn't result in Error

alternative compile your code with #ifdef DEBUG_TASMOTA_SENSOR (only for devs, blow up the code) and use `Weblog 3` will return additonal infos on console ("NEO: NeoPoolInit no GPIOs assigned" and "NEO: NeoPoolInit Modbus init failed xx")

**Comment by curzon01** [comment]
suggestion: use #ifndef/#undef everywhere

```C++
...
// [SensorRetain] Sensor may send retain flag (false = off, true = on)
#undef MQTT_SENSOR_RETAIN
#define MQTT_SENSOR_RETAIN     true

// Add support for rules (+8k code)
#ifndef USE_RULES
#define USE_RULES
#endif
...
```

**Comment by curzon01** [comment]
> This happens also when GPIO tx/rx are not configured, but they are actually, so it seems it's a compilation issue, but I'm not sure.

Hint: If NeoPool sensor isn't compiled, you can't select "NeoPool Tx/Rx", it's not there - so if you can select "NeoPool Tx/Rx" from the GPIO dropdown list and assign, Tasmota is compiled with NeoPool

**Comment by alexdelprete** [comment]
> Hint: If NeoPool sensor isn't compiled, you can't select "NeoPool Tx/Rx", it's not there - so if you can select "NeoPool Tx/Rx" from the GPIO dropdown list and assign, Tasmota is compiled with NeoPool

Good hint. So if in GPIO config I see the two pins correctly assignes, it means I can assume NeoPool has been compiled. Simple solution. :)

But NP commands still throw an error, maybe that's because there's no connection to modbus. If the answer to commands is unknown, probably that means NeoPool module has not been included.

**Comment by curzon01** [comment]
other answers tomorrow iam on the way

**Comment by curzon01** [comment]
> This is not very clear

- with compiled NEOPOOL module
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/6636844/a15f872d-a6f5-4117-bf34-19709765643b)

- without compiled NEOPOOL module
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/6636844/9bc7c4ee-67a7-41c3-a539-c85c542c856d)

- this, for example, indicates absolutely nothing
(you can't know whether it's compiled in or not, the missing assignment to GPIOs may have other reasons):
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/6636844/477c032b-c211-41b1-896f-6e245bb1235f)

- this is definately a Tasmota with compiled NEOPOOL moduel:
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/6636844/8c55bccc-947b-4b4f-8a9e-188a0d2b904f)

- this is definately NOT compiled in
(this happens using Tasmota without compiled NEOPOOL module and if GPIOs were previously assigned or forced assigned using Tasmota console e.g. Template):
![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/6636844/6db4c35e-865f-44c5-b932-dc519c84044a)

NPxxx command results:
- compiled without NEOPOOL module:
`{"Command":"Unknown"}`
- compiled with NEOPOOL module, GPIOs unassigned:
`{"Command":"Unknown"}`
- compiled with NEOPOOL module, GPIOs assigned, no device connected:
`{"NPTime":"Error"}`

### Conclusion

- you can't recognize with NPxxx command result alone whether Tasmota was compiled with or without NEOPOOL modules because NPxxxx can return `"Unknown"` in both cases.
The only indications if NEOPOOL module is compiled are 
  - decode-status.p returns USE_NEPOOL
  - dropdown list shows "NeoPool Tx/Rx"
  - visible GPIO(s) assignement to "NeoPool Tx/Rx"
  - NPxxxx commands return `"Error"` instead `"Unknown"`
- if NPxxxx returns "Error" means always that Tasmota is basically ready to work with NeoPool and NeoPool Tx/Rx are assigned to any GPIOs but there is not communication due to
  - wiring is wrong
  - RS485 interfacing is wrong
  - device is not connected
  - does not answer for any other reason

**Comment by curzon01** [comment]
> is there a specific reason? It's how the compiler works?

these are pre-compiler macro directives and can (but do not necessarily have to) lead to warnings or subsequent warnings/errors if they are already defined elsewhere

> I'm a bit unsure about #undef/#define MODULE, is it correct?

this works

**Comment by alexdelprete** [comment]
Last evening I was trying to make my `user_config_override.h` work, and it seems everything is ok except one critical thing: the user template is being configured correctly, but the module is not configured to use the template on first boot.

I followed a post of one of the tasmota devs to make sure to have the equivalent of `Module 0`, but it isn't working, the other module is active on first boot instead of the template. :(

Do you see anything wrong in this section?

```cpp
// [Template] Set JSON user template for GPIO configuration (Atom+Tail and ESP8266)

// Define Template based on chip
#ifdef USER_TEMPLATE
  #undef USER_TEMPLATE
#endif

#ifdef ESP32
  #define USER_TEMPLATE "{\"NAME\":\"NeoPool Atom Lite + Tail485\",\"GPIO\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,6976,0,0,0,0,0,7008,1,0,0,0,0,0,0],\"FLAG\":0,\"BASE\":1}"
#endif  // ESP32

#ifdef ESP8266
  #warning **** Template: NeoPool ESP8266 ****
  #define USER_TEMPLATE "{\"NAME\":\"NeoPool ESP8266\",\"GPIO\":[1,6528,1,6496,1,1,0,0,1,1,1,1,1,1],\"FLAG\":0,\"BASE\":18}"
#endif  // ESP8266

// Activate User Template
#ifdef MODULE
  #undef MODULE
#endif
#define MODULE                 USER_MODULE   // [Module] Select default model (the list is kModuleNiceList() in file tasmota_template.h) USER_MODULE is the TEMPLATE

#ifdef FALLBACK_MODULE
  #undef FALLBACK_MODULE
#endif
#define FALLBACK_MODULE        USER_MODULE   // to Select the default model as FALLBACK when the user does a RESET 1
```

**Comment by alexdelprete** [comment]
> * because NPxxxx can return `"Unknown"` in both cases.

while experimenting with Module / Template activation at boot, I found out the following on one specific command (NPTeleperiod), I guess it has to do with the fact that it doesn't involve the external device so its behavior is a little different vs other commands.

```console
22:47:55.433 CMD: module
22:47:55.437 MQT: stat/DevSmartPool/RESULT = {"Module":{"1":"ESP32-DevKit"}}
22:48:21.485 CMD: NPteleperiod
22:48:21.491 MQT: stat/DevSmartPool/RESULT = {"Command":"Unknown"}
22:48:24.235 CMD: NPtime
22:48:24.241 MQT: stat/DevSmartPool/RESULT = {"Command":"Unknown"}

22:49:55.319 CMD: Module 0
22:49:55.323 MQT: stat/DevSmartPool/RESULT = {"Module":{"0":"NeoPool Atom Lite + Tail485"}}
22:50:19.420 CMD: NPTime
22:50:19.577 MQT: stat/DevSmartPool/RESULT = {"NPTime":"Error"}
22:50:23.758 CMD: NPteleperiod
22:50:23.766 MQT: stat/DevSmartPool/RESULT = {"NPTelePeriod":60}
```

**Comment by curzon01** [comment]
mea culpa, NPxxxx excludes NPTelePeriod, NPOnError, NPPHRes, NPCLRes, NPIONRes

**Comment by alexdelprete** [comment]
I updated the readme with new configuration instructions, I tested it on a couple of Atom Lite and it's consistently working. I will later add instructions for custom compilation with `user_config_override.h`.

I'd love to solve last config task: including in some way the berry scripts at compilation time, if possible, or in alternative with some commands.
