### ISSUE TITLE
NeoPool Documentation about Relays

### ISSUE THREAD

**Issue by alexdelprete** [alexdelprete/HA-NeoPool-MQTT#5]
@curzon01 In regard to relays, I implemented the HA integration based on this code I found in the driver:

```
// MBF_RELAY_STATE
  MBMSK_RELAY_STATE1                      = 0x0001, //  0 Relay 1 state (1 on; 0 off) (normally assigned to ph)
  MBMSK_RELAY_STATE2                      = 0x0002, //  1 Relay 2 state (1 on; 0 off) (normally assigned to filtering)
  MBMSK_RELAY_STATE3                      = 0x0004, //  2 Relay 3 status (1 on; 0 off) (normally assigned to lighting)
  MBMSK_RELAY_STATE4                      = 0x0008, //  3 Relay 4 status (1 on; 0 off)
  MBMSK_RELAY_STATE5                      = 0x0010, //  4 Relay 5 status (1 on; 0 off)
  MBMSK_RELAY_STATE6                      = 0x0020, //  5 Relay 6 status (1 on; 0 off)
  MBMSK_RELAY_STATE7                      = 0x0040, //  6 Relay 7 status (1 on; 0 off)
```

And I had confirmation reading the SV register map document:

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/5079e624-b045-466b-be5d-d8496edc8bb2)

So we have 3 relays normally assigned + 4 AUX relays that are configurable by the user.

In NeoPool docs I read this about relays and `NPControl` command:

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/49f8ff83-369b-42b6-8b21-69212ddbd4ad)

The list of Relays doesn't match the above, and the output of NPControl on my system is effectively wrong regarding the state of relays. I have filtering on right now, but the NPControl command says my Acid relay is on:

```json
    "Relay": {
      "State": [
        0,
        1,
        0,
        0,
        0,
        0,
        0
      ],
      "Aux": [
        0,
        0,
        0,
        0
      ],
      "Acid": 0
    }
```

```json
`NPControl` result:
{
    "Modules": {
        "pH": 1,
        "Redox": 1,
        "Hydrolysis": 1,
        "Chlorine": 0,
        "Conductivity": 0,
        "Ionization": 0
    },
    "Relay": {
        "Acid": 1,
        "Base": 0,
        "Redox": 0,
        "Chlorine": 0,
        "Conductivity": 0,
        "Heating": 0,
        "UV": 0,
        "Valve": 0
    }
}
```

Furthermore, reading the json, it could seem that we have 11 relays (7 + 4 aux), while the aux are part of the 7. So why a separate section for AUX? 

Thanks,

Alessandro

**Comment by curzon01** [comment]
For what do you need NPControl command? This inform is historical and kept in for backward compaitibliy. You doesn't need NPControl information, that's all in SENSOR.

> The list of Relays doesn't match the above

right, forget NPControl, the "Relays" output is buggy

> Furthermore, reading the json, it could seem that we have 11 relays (7 + 4 aux), while the aux are part of the 7. So why a separate section for AUX?

historical, preventing change breaking, but it's documented:

Relay.State | (Array) Relay states for all possible seven relays 1-7 (functional independent)
-- | --
Relay.Aux | (Array) Relay states for the 4 Aux relais (these are the same as `Relay.State`` 4-7 - functional independent)

**Comment by alexdelprete** [comment]
> right, forget NPControl, the "Relays" output is buggy

No problem, it was just because I was testing some commands and I found the docs were misleading. I didn't know you were aware of this so I preferred to tell you anyway.

> Be aware, you can (it's not easy but it's possible) freely assign the 7 physical relays in SV, also filtration, light and acid pump.

Yes I read about this. Thanks for the heads-up.

**Comment by curzon01** [comment]
>> right, forget NPControl, the "Relays" output is buggy

> No problem, it was just because I was testing some commands and I found the docs were misleading. I didn't know you were aware of this so I preferred to tell you anyway.

My info is wrong (it's all too long ago) and the output from NPControl is correct (not buggy):

The data for the relays from NPControl do not show the state but the function assignment. I have already updated the documentation [for this point](https://tasmota.github.io/docs/NeoPool/#sensor-data).
