### ISSUE TITLE
Aux relays: binary_sensors or switches?

### ISSUE THREAD

**Issue by alexdelprete** [alexdelprete/HA-NeoPool-MQTT#8]
@curzon01 Norbert, I was thinking that `Aux` relays, which are controllable via `NPAux` command, should be switches instead of binary_sensors like I currently configured them. Do you agree?

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/68a1dca0-1a21-4676-8467-b9aa3f34ca79)

**Comment by curzon01** [comment]
aux are switches

**Comment by alexdelprete** [comment]
Also Filter & Light, but I have them both as binary_sensors and switches.

So, among all relays, only Acid & pH are not switches, correct?

**Comment by curzon01** [comment]
Unfortunately it's not that simple with the relays, it took me also some time to understand the logic of SV regarding the relays.
Also my statement, that the aux are switches, refers only to the current implementation of NPAux with on/off, which is , unfortunately, incomplete  - besides the ESP82xx argument this is also the real reason, that NPAux is present as a Berry example and not finally in the source code:
The Aux allows two other modes besides the manual on/off function (check your system), can be labeled and if someone uses these modes, the NPAux command will reset them to manual mode.

With the other relays I have not yet noted that your fixed designation pH, Filter, Light, Acid is not so fixed. The assignment of the relays to these functionalities are free and do not have to match in other systems.

I know you want to push this forward and finalize it, but I also want to prevent massive design errors. But I can't continue the time I spent the last days, I just have too many other points of professional nature at the moment. You can try to continue the things that are unknown to you, but you have to expect that they will be incomplete or completely wrong.

Some relay related things are currently mapped in the SENSOR json and NPControl output, but not all. If you want to leave it like for the time being with the display of the relays and aux as a switch, then you must be aware that this will not fit with all system configurations and users may change functions that are not wanted like this.

I will first do the Hydrolysis staff in NeoPool module the next days.

**Comment by alexdelprete** [comment]
> I know you want to push this forward and finalize it, but I also want to prevent massive design errors

My intention is to do things properly, I don't want to rush anything. Sorry if I gave the impression to push things because I want to complete it quickly, that is not the case.

> But I can't continue the time I spent the last days, I just have too many other points of professional nature at the moment. You can try to continue the things that are unknown to you, but you have to expect that they will be incomplete or completely wrong.

Norbert, I didn't mean to push you in any way, I didn't expect you to react so quickly to my solicitations, and I thank you for that, but it was not my intention to distract you from your professional and private obligations. Take your time, nothing is urgent here, also because the important stuff works. There are things to do but there's no rush.

> I will first do the Hydrolysis staff in NeoPool module the next days.

Thanks, once that stuff is in, I think we reached a pretty good state. The rest can wait. :)

Good night.
